---
title: "classification_experiement_v9 - implement DIMVf"
output:
  pdf_document: default
  html_document: default
date: "2022-09-30"
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE, echo=TRUE, eval = TRUE)
``` 


```{r}
require(knitr)
FILE_NAME = 'v12'
purl("imputation.Rmd", output = 'imputation.R')
```

```{r}

packages <- c(
  "missMDA", 
  "softImpute", 
  "caret", 
  "caTools", 
  "glue", 
  "jsonlite", 
  "future.apply", 
  "dslabs", 
  "cowplot", 
  "magick", 
  "progress"
)
# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE)) 

library(here) 
source(here('src/rscript/dimv.R'))  
source(here('src/rscript/dpers.R'))   
source(here('src/rscript/utils.R'))    
source(here('src/rscript/imputation_comparation.R'))     

plan(multisession, workers = 8)  

```



```{r}
processed_data = processing_mnist_data()
train = processed_data$train 
test = processed_data$test
X.train = train[, -785]
X.test = test[, -785]
y.train = train[, 785, drop=F]
y.test = test[, 785, drop=F] 
``` 


# DATA PREPARATION
## READING DATA : 

## CREATE NON RANDOM MISSING VALUE 

```{r}
get_image_position_spatial_to_flatten<- function(delImgPosWidth, delImgPosHeight){ 
  # delImgPosHeight: row 
  # delImgPosWeight : col 
  tmp = c(1:784)
  im <- matrix(unlist(tmp),nrow = 28,byrow = T)
  idxs = im[delImgPosHeight, delImgPosWidth]  
  return(matrix(idxs,nrow = 1,byrow = T)[, ])
}
```  

```{r}
image_edge_deleting <- function(
    data, 
    delete_type, #by_percent, by_pixel_number 
    percents_of_data,
    image_width,
    image_height,
    width_del_percent=0, 
    height_del_percent=0,
    from_pixel_width=None, 
    from_pixel_height=None
    ){
  if (delete_type =='by_percent'){
    n = dim(data)[2]
    from_pixel_width = ceiling((1-width_del_percent)*image_width)   
    from_pixel_height = ceiling((1-height_del_percent)*image_height)
  }
  if (delete_type=='by_pixel_number'){
    from_pixel_width = from_pixel_width
    from_pixel_height = from_pixel_height
  }
  
flatten_columns_removed = get_image_position_spatial_to_flatten(
  from_pixel_width:image_width,
  from_pixel_height: image_height
)

  flatten_rows_removed = sample.int(nrow(data), as.integer(nrow(data)*percents_of_data))
  missing_data = data
  missing_data[flatten_rows_removed, flatten_columns_removed] <- NA
  result = list(
    'missing_data'=missing_data, 
    'flatten_columns_removed'=flatten_columns_removed,  
    'flatten_rows_removed'=flatten_rows_removed
  ) 
  return(result)
}

``` 


```{r, fig.width = 6, fig.height=1.2}
# visualize the deleted images 
visualize_digit <- function(missing_X, y, train_removed_rows, per_col=1, per_row=8, title=""){

  par(mfcol=c(per_col, per_row))
  par(mar=c(0, 0, 3, 0), xaxs='i', yaxs='i')  
 
  for (idx in 1:(per_col*per_row)) { 
      im <- matrix(unlist(missing_X[train_removed_rows, ][idx, ]),nrow = 28 ,byrow = T)
      im <- t(apply(im, 2, rev)) 
      image(1:28, 1:28, im,  xaxt='n', main=paste(y[train_removed_rows,,drop=F][idx, ])) 
      
      #image(1:28, 1:28, im, col=gray((0:255)/255), xaxt='n', main=paste(y[train_removed_rows,,drop=F][idx, ]))
  }

}
```

```{r, fig.width = 6, fig.height=1.2}
p1 <- visualize_digit(softImpute_Xtest_recon, y_test, test_removed_rows, 1, 8) 
```
```{r, fig.width = 6, fig.height=1.2}
visualize_digit(impDi_Xtest_recon, y_test, test_removed_rows, 1, 8) 
``` 




```{r}
# get_test_softImpute <- read.csv(
#   file.path('../../../data/mnist/plot/softImpute_threshold_10_deletedWidthHeightPc_6060_noImagePc_50.csv'))[, 2:785]
```

```{r, fig.width = 6, fig.height=1.2}
visualize_digit(get_test_softImpute, y_test, test_removed_rows)
```

```{r, fig.width = 6, fig.height=1.2} 
visualize_digit(Gain_recon, y_test, test_removed_rows, 1,8)
```


```{r}
normalizing <- function(x=None, Xtrain=None){
  na_mask = is.na(x)
  mean = apply(Xtrain, 2, mean, na.rm=TRUE)
  sd = apply(Xtrain, 2, sd, na.rm=TRUE)
  
  sd_equal_zero_mask = which(sd==0)
  subtract_mean = sweep(x, 2, mean, '-')
  X_normed = sweep(subtract_mean, 2, sd, "/")
  
  X_normed[is.na(X_normed)] = 0 
  X_normed[is.infinite(X_normed)] = 0 
  X_normed[na_mask] = NA 
  result = list('X_normed'=X_normed, 'mean'=mean, 'sd'=sd, 'sd_equal_zero_mask'=sd_equal_zero_mask)
  return (result) 
} 
```


```{r}

sampling_data <- function(data, y_col_name, sample_perc){
  data$label= data[, y_col_name]
  sample_indices <- sample.split(Y=data[, 'label'], SplitRatio = sample_perc)
  sample_data <- as.data.frame(subset(data, sample_indices == TRUE))
  result = list(
    'sample'=sample_data, 
    'X'=as.matrix(sample_data[, 1:(28*28)]), 
    'y'=sample_data[,'label', drop=F]
  )
  return(result)
}

```

Normalizing train and test using train 's parameters 
```{r}
normalizing <- function(x=None, Xtrain=None){
  na_mask = is.na(x)
  mean = apply(Xtrain, 2, mean, na.rm=TRUE)
  sd = apply(Xtrain, 2, sd, na.rm=TRUE)
  
  sd_equal_zero_mask = which(sd==0)
  subtract_mean = sweep(x, 2, mean, '-')
  X_normed = sweep(subtract_mean, 2, sd, "/")
  
  X_normed[is.na(X_normed)] = 0 
  X_normed[is.infinite(X_normed)] = 0 
  X_normed[na_mask] = NA 
  result = list('X_normed'=X_normed, 'mean'=mean, 'sd'=sd, 'sd_equal_zero_mask'=sd_equal_zero_mask)
  return (result) 
}

reconstructingNormedMatrix <- function(X_norm, mean, std){
  mult = sweep(X_norm, 2, std, '*')
  reconstrc = sweep(mult, 2, mean, '+')
  return (reconstrc)
} 
```



```{r}
dim(gain_random)
```

```{r}
visualize_digit(gain_random, y_test, 1:100, 2,6, "GAIN - Randomly missing data at missing rate 0.36")
 
```


```{r}

visualize_digit(softImpute_Xtest_recon, y_test, as.vector(test_removed_rows)$test_removed_rows, 2,6)

```

```{r}
visualize_digit(impDi_Xtest_recon, y_test, as.vector(test_removed_rows)$test_removed_rows, 2,6)
```


```{r}
visualize_digit(Gain_Xtest_recon, y_test, as.vector(test_removed_rows)$test_removed_rows, 2,6, title = 'GAIN' )

```

```{r}
X_test_normed = read.csv(file.path(sub_path, 'X_test_normed.csv'))
X_test_normed
```

```{r}
visualize_digit(X_test_normed, y_test, test_removed_rows, 2,6)
```


```{r}
Gain_Xtest = read.csv(file.path(sub_path, 'test_Gain.csv'))[,2:785,drop=F]

```

```{r}
visualize_digit(Gain_Xtest, y_test, as.vector(test_removed_rows)$test_removed_rows, 2,6)
```




```{r}


width_del = 50
heigh_del = 50
percent_img_del = 50  
threshold_string = 10 

 
sub_folder = paste0(
    "threshold_", 
    threshold_string, 
    "_deletedWidthHeightPc_", 
    width_del, 
    heigh_del, 
    '_noImagePc_', 
    percent_img_del
  ) 


FILE_NAME = 'v12' 
curr_dir = getwd() 
main_dir = paste0('../../../data/mnist/imputed/', FILE_NAME,'/')

random_dir = paste0("../../../data/train_01.csv")
sub_path = file.path(curr_dir, main_dir, sub_folder) 


impDi_Xtest_recon = read.csv(file.path(sub_path, 'test_impDi_Xrecon.csv'))
softImpute_Xtest_recon = read.csv(file.path(sub_path, 'test_softImpute_Xrecon.csv')) 
#GAIN_Xtest_recon = read.csv(file.path(sub_path, 'test_Gain_Xrecon.csv'))[,2:785,drop=F]


test_removed_rows = as.vector(read.csv(file.path(sub_path, 'test_removed_rows.csv')))$test_removed_rows 
y_test = read.csv(file.path(sub_path, 'y_test.csv')) 

gain_random = read.csv(file.path(random_dir)) 

# RESCONSTRUCTING gain.py 
y_train = read.csv(file.path(sub_path, 'y_train.csv')) 
train_ori = read.csv(file.path("../../../data/mnist/original/Xtrain.csv"))
train_missing_normed = read.csv(file.path(sub_path, 'X_train_normed.csv'))
train_removed_rows = as.vector(read.csv(file.path(sub_path, 'train_removed_rows.csv')))$train_removed_rows 
GAIN_Xtest = read.csv(file.path(sub_path, 'test_Gain.csv')) 


get_normalization_parameters <- function(Xtrain){
  mean = apply(Xtrain, 2, mean, na.rm=TRUE)
  sd = apply(Xtrain, 2, sd, na.rm=TRUE) 
  result = list("mean" = mean, "sd" = sd)
} 

train_ori[is.na(train_missing_normed)] <- NA  
params = get_normalization_parameters(train_ori)
train_mean = params$mean
train_sd = params$sd



GAIN_Xtest_recon = reconstructingNormedMatrix(GAIN_Xtest,train_mean, train_sd)
test_ori = read.csv(file.path("../../../data/mnist/original/Xtest.csv"))

test_missing_normed = read.csv(file.path(sub_path, 'X_test_normed.csv'))
test_ori_missing = test_ori 
test_ori_missing[is.na(test_missing_normed)] <- NA  

```


```{r, fig.width = 6, fig.height=1.2}
plot_path = file.path(paste0("../../../data/mnist/plot/", sub_folder))
if (dir.exists(plot_path)==F){
  dir.create(plot_path)
} 
OriImgPath <- file.path(plot_path, "ori_test.png")  
png(OriImgPath, width = dev.size("px")[1], height = dev.size("px")[2]) 
visualize_digit(test_ori, y_test, test_removed_rows, 1, 8) 
dev.off()

OriMissingImgPath <- file.path(plot_path, "ori_missing_test.png")  
png(OriMissingImgPath, width = dev.size("px")[1], height = dev.size("px")[2]) 
visualize_digit(test_ori_missing, y_test, test_removed_rows, 1, 8) 
dev.off() 

softImputeImgPath <- file.path(plot_path, "softImpute_test.png") 
png(softImputeImgPath, width=dev.size("px")[1] , height = dev.size("px")[2])  
visualize_digit(softImpute_Xtest_recon, y_test, test_removed_rows, 1, 8) 
dev.off()

GainImgPath <- file.path(plot_path, "Gain_test.png")  
png(GainImgPath, width = dev.size("px")[1], height = dev.size("px")[2]) 
visualize_digit(GAIN_Xtest_recon, y_test, test_removed_rows, 1, 8) 
dev.off() 
 
impDiImgPath <- file.path(plot_path, "impDi_test.png")  
png(impDiImgPath, width = dev.size("px")[1], height = dev.size("px")[2]) 
visualize_digit(impDi_Xtest_recon, y_test, test_removed_rows, 1, 8) 
dev.off()


 
merged_width = 300 #dev.size("px")[1]
merged_height = 300*5+50 #dev.size("px")[2]*2+50
```




```{r, fig.width = 6, fig.height=1.2*5}
p1 <- ggdraw() + draw_image(OriImgPath)
p2 <- ggdraw() + draw_image(OriMissingImgPath)
p3 <- ggdraw() + draw_image(softImputeImgPath)
p4 <- ggdraw() + draw_image(GainImgPath) 
p5 <- ggdraw() + draw_image(impDiImgPath)  
  
imgPath =  file.path(plot_path, "img.png")  

png(imgPath) #,  width = merged_width, height = merged_height) 

plot_grid(p1, p2, p3, p4, p5, 
          nrow = 5, 
          ncol=1,
          labels =  NULL, 
          label_size = 12, 
          scale=1,
          vjust=c(2.0, 2.0, 2.0, 2.0),
          label_colour = "blue")

dev.off()
# 
print(paste0("Complete saving plot, pipeline is done ", sub_folder)) 
```


